#!/usr/bin/env node

const createDb = require('../server/db');
const ingester = require('../api/datasources/ingester');
const log = require('../server/log');

const MINUTES = 60 * 1000;

log.info("Performing ingest by script..");

const db = createDb({
  options: {
    requestTimeout: 10 * MINUTES
  }
});

let exitCode = 0;
ingester.ingest(db)
  .then(() => log.info("done."))
  .catch((err) => {
    log.error(err);
    exitCode = 1;
  })
  .then(() => process.exit(exitCode));

