---
  swagger: "2.0"
  info:
    title: "Analytics API"
    version: "0.0.1"
    description: "Provides the ability to query analytics results sets"
  host: "viper-dev.hmpps.dsd.io"
  basePath: "/"
  schemes:
    - "http"
    - "https"
  paths:
    /offender/{nomsId}/viper:
      parameters:
        - in: "path"
          name: "nomsId"
          required: true
          type: "string"
          pattern: "[A-Z]\\d{4}[A-Z]{2}"
          description: "A known NOMS ID"
          x-example: "A1234BC"
      get:
        x-swagger-router-controller: offender
        operationId: retrieveViperRating
        summary: "Retrieve VIPER Rating"
        description: "Retrieves a single VIPER Rating from the dataset"
        responses:
          200:
            description: "Success"
            examples:
              application/json:
                nomsId: "A1234BC"
                viperRating: 0.56
            schema:
              "$ref": "#/definitions/viperRatingSuccess"
          500:
            description: "Invalid NOMS Id"
            examples:
              application/json:
                message: "Request validation failed: Parameter (nomsId) does not match required pattern: [A-Z]\\d{4}[A-Z]{2}"
            schema:
              "$ref": "#/definitions/invalidArgumentError"
          404:
            description: "Not Found"
            examples:
              application/json:
                message: "Resource Not Found"
            schema:
              "$ref": "#/definitions/notFoundError"
        tags:
          - "VIPER Rating"
        produces:
          - "application/json"
  definitions:
    viperRatingSuccess:
      type: "object"
      properties:
        nomsId:
          type: "string"
          description: "A valid NOMS ID"
          pattern: "[A-Z]\\d{4}[A-Z]{2}"
          example: "A1234BC"
        viperRating:
          type: "number"
          description: "A percentile VIPER Rating"
          example: 0.56
      required:
        - "nomsId"
        - "viperRating"
    invalidArgumentError:
      type: "object"
      properties:
        code:
          type: "string"
          description: "A status code description"
          example: "Invalid Argument"
        message:
          type: "string"
          description: "A message detailing the error"
          example: "Request validation failed: Parameter (nomsId) does not match required pattern: [A-Z]\\d{4}[A-Z]{2}"
      required:
        - "message"
    notFoundError:
      type: "object"
      properties:
        code:
          type: "string"
          description: "A status code description"
          example: "Not Found"
        message:
          type: "string"
          description: "A message detailing the error"
          example: "Resource Not Found"
      required:
        - "message"
