---
  swagger: "2.0"
  info:
    title: "Analytics API"
    version: ""
    description: "Provides the ability to query analytics results sets\n\nFORMAT: 1A\nHOST: http://viper-dev.hmpps.dsd.io"
  host: "viper-dev.hmpps.dsd.io"
  basePath: "/"
  schemes:
    - "http"
  paths:
    /offender/{nomsId}/viper:
      get:
        x-swagger-router-controller: offender
        operationId: retrieveViperRating
        responses:
          200:
            description: "Success"
            headers: {}
            examples:
              application/json:
                nomsId: "A1234BC"
                viperRating: 0.56
            schema:
              type: "object"
              properties:
                nomsId:
                  type: "string"
                  description: "A valid NOMS ID"
                viperRating:
                  type: "number"
                  description: "A percentile VIPER Rating"
              required:
                - "nomsId"
                - "viperRating"
        summary: "Retrieve VIPER Rating"
        description: "Retrieves a single VIPER Rating from the dataset"
        tags:
          - "VIPER Rating"
        parameters:
          -
            name: "nomsId"
            in: "path"
            description: "A known NOMS ID"
            required: true
            type: "string"
        produces:
          - "application/json"
  definitions:
    Retrieve VIPER Rating: {}
