version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/app
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
          key: node_modules
      - run:
          name: Install Dependencies
          command: |
            npm prune
            npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
