version: 2

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: /deploy-to.*/
      - publish_artifact:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_to_dev:
          requires:
            - publish_artifact

defaults: &defaults
  working_directory: /home/circleci/app

jobs:
  build:
    <<: *defaults
    docker:
      - image: &image circleci/node:6
      - image: microsoft/mssql-server-linux:ctp2-1
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: aRubbishPasswordForC1Only
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
          key: node_modules
      - run:
          name: Install Dependencies
          command: |
            npm prune
            npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Check for security advisories
          command: npm run snyk
      - run:
          name: Initialise SQL Server
          command: |
            npm run setup-mssql
            npm run migrate
          environment:
            DB_URI: mssql://sa:aRubbishPasswordForC1Only@localhost:1433/viper
            APP_USER: app
            APP_PASSWORD: aRubbishPasswordForC1Only
      - run:
          name: Run Unit Tests
          command: npm run test-report
          environment:
            MOCHA_FILE: build/junit/test-results.xml
            DB_URI: mssql://app:aRubbishPasswordForC1Only@localhost:1433/viper
      - store_test_results:
          path: build
      - run:
          name: Seed database
          command: npm run seed
          environment:
            DB_URI: mssql://sa:aRubbishPasswordForC1Only@localhost:1433/viper
      - run:
          name: Dredd Tests
          command:
            npm run docs-test
          environment:
            DB_URI: mssql://app:aRubbishPasswordForC1Only@localhost:1433/viper
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  publish_artifact:
    <<: *defaults
    docker:
      - image: *image
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - run:
          name: Record Build info
          command: |
            export GIT_REF=$CIRCLE_SHA1
            export BUILD_NUMBER=$CIRCLE_BUILD_NUM
            npm run record-build-info
      - deploy:
          name: Build Derived Git Commit
          command: |
            git add --force --verbose build-info.json
            git config user.name "Circle CI"
            git config user.email "circle@circleci.com"
            git commit \
              -m "Deployment of build $CIRCLE_BUILD_NUM" \
              -m "$(git log --format=%B -n 1 $CIRCLE_SHA1)" \
              -m "From gitref $CIRCLE_SHA1"

  deploy_to_dev:
    <<: *defaults
    docker:
      - image: *image
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to Dev environment
          command: |
            export DB_URI=$DEV_DB_URI
            npm run knex -- migrate:currentVersion
            npm run migrate
            npm run seed
            git push --force origin HEAD:deploy-to-dev
