version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: microsoft/mssql-server-linux:ctp2-1
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: aRubbishPasswordForC1Only
    working_directory: ~/app
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
          key: node_modules
      - run:
          name: Install Dependencies
          command: |
            npm prune
            npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit Tests
          command: npm run test-report
          environment:
            MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
      - run:
          name: Initialise SQL Server
          command: |
            npm run setup-mssql
            npm run knex -- migrate:currentVersion
            npm run migrate
            npm run seed
          environment:
            DB_URI: mssql://sa:aRubbishPasswordForC1Only@localhost:1433/viper
            APP_USER: app
            APP_PASSWORD: aRubbishPasswordForC1Only
      - run:
          name: Dredd Tests
          command: npm run docs-test
          environment:
            DB_URI: mssql://app:aRubbishPasswordForC1Only@localhost:1433/viper
