FORMAT: 1A
HOST: http://viper-dev.hmpps.dsd.io

## Group VIPER Rating

The Violence in Prison Estimator Rating

### Record VIPER Rating [POST /offender/viper]

Records a single VIPER Rating from the dataset

+ Request Record a single VIPER Rating record (application/json)

    + Body
        + Parameters
            + nomsId: `A1234BC`
            + viperRating: 0.56

    + Schema

        {
            "type": "object",
            "properties": {
                "nomsId": {
                    "type": "string",
                    "description": "A valid NOMS ID"
                },
                "viperRating": {
                    "type": "number",
                    "description": "A percentile VIPER Rating"
                }
            },
            "required": [
                "nomsId",
                "viperRating"
            ]
        }

+ Response 201 (application/json)

    Created

    + Headers

            Location: /offender/A1234BC/viper

    + Attributes (VIPERRating)
        + nomsId: `A1234BC`
        + viperRating: 0.56 (number)

### Retrieve VIPER Rating [GET /offender/{nomsId}/viper]

Retrieves a single VIPER Rating from the dataset

+ Parameters
    + nomsId: `A1234BC` (string, required) - A known NOMS ID

+ Request Known nomsId (application/json)
    + Parameters
        + nomsId: `A1234BC`

+ Response 200 (application/json)

    Success

    + Attributes (VIPERRating)
        + nomsId: `A1234BC`
        + viperRating: 0.56 (number)

+ Request Unknown nomsId (application/json)
    + Parameters
        + nomsId: `C4321BA`

+ Response 404 (application/json)

    Resource Not Found

    + Attributes (HTTPStatusMessage)
        + code: `ResourceNotFound`
        + message: `/offender/C4321BA/viper does not exist`

+ Request Invalid nomsId (application/json)
    + Parameters
        + nomsId: `1ABCD23`

+ Response 409 (application/json)

    Invalid Argument

    + Attributes (HTTPStatusMessage)
        + code: `InvalidArgument`
        + message: `nomsId (INVALID): Invalid characters`

## Data Structures

### VIPERRating

+ nomsId (string, required) - A valid NOMS ID
    + pattern: `A1234BC`
+ viperRating (number, required) - A percentile VIPER Rating

### HTTPStatusMessage

+ code (string, required) - HTTP Status Code
+ message (string, required) - Description of status
